# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import loctaion_pb2 as loctaion__pb2


class LocationStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLocationByTimestamp = channel.unary_unary(
                '/location.Location/GetLocationByTimestamp',
                request_serializer=loctaion__pb2.LocationByTimestampReq.SerializeToString,
                response_deserializer=loctaion__pb2.LocationReply.FromString,
                )


class LocationServicer(object):
    """The greeting service definition.
    """

    def GetLocationByTimestamp(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLocationByTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationByTimestamp,
                    request_deserializer=loctaion__pb2.LocationByTimestampReq.FromString,
                    response_serializer=loctaion__pb2.LocationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'location.Location', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Location(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetLocationByTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/location.Location/GetLocationByTimestamp',
            loctaion__pb2.LocationByTimestampReq.SerializeToString,
            loctaion__pb2.LocationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
